# Generated by Django 4.2.2 on 2023-07-05 16:15

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('Buy', 'Buy'), ('Do', 'Do'), ('Meet', 'Meet')], max_length=20)),
                ('status', models.CharField(choices=[('O', 'Open'), ('R', 'Reserved'), ('I', 'In Progress'), ('D', 'Done'), ('C', 'Closed')], default='O', max_length=1)),
                ('request_date', models.DateField()),
                ('request_start_time', models.TimeField()),
                ('request_end_time', models.TimeField()),
                ('request_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3)),
                ('request_price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=6)),
                ('request_stars', models.IntegerField(blank=True, choices=[(5, 'Excellent'), (4, 'Above average'), (3, 'Average'), (2, 'Below average'), (1, 'Poor')], null=True)),
                ('work_stars', models.IntegerField(blank=True, choices=[(5, 'Excellent'), (4, 'Above average'), (3, 'Average'), (2, 'Below average'), (1, 'Poor')], null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='works', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnockChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=1)),
                ('knock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='knock.knock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('request_stars', models.FloatField(blank=True, null=True)),
                ('work_stars', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnockSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('knock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knock.knock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnockChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=1024)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='knock.knockchat')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='knock',
            name='submits',
            field=models.ManyToManyField(through='knock.KnockSubmit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='knock',
            constraint=models.CheckConstraint(check=models.Q(('request_start_time__lt', models.F('request_end_time'))), name='request_start_time must be less than request_end_time'),
        ),
    ]
