# Generated by Django 4.2.2 on 2023-07-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='knock',
            name='request_start_time must be less than request_end_time',
        ),
        migrations.AddConstraint(
            model_name='knock',
            constraint=models.CheckConstraint(check=models.Q(('request_start_time__lt', models.F('request_end_time'))), name='request_start_time must be less than request_end_time', violation_error_message='End time must be after Start time'),
        ),
    ]
